import Head from "next/head";
import Image from "next/image";
import Login from "../components/authentication/Login";
import Header from "../components/Header/Header";
import { getSession } from "next-auth/client";
import Slidebar from "../components/SlideBar/Slidebar";
import Feed from "../components/Feed/Feed";
import Contacts from "../components/Contacts/Contacts";
import { db } from "../firebase";
import { ThemeProvider } from "../components/hooks/ThemeContext";

export default function Home({ session, posts }) {
  if (!session) return <Login />;
  console.log(session);
  return (
    <ThemeProvider>
      <div>
        <Head>
          <title>Facebook Clone By Xuan Hau</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className="flex justify-between mx-2 dark:-[#18191a]">
          <Slidebar />
          <Feed posts={posts} />
          <Contacts />
        </main>
      </div>
    </ThemeProvider>
  );
}

export async function getServerSideProps(context) {
  //set user
  const session = await getSession(context);
  const posts = await db.collection("post").orderBy("timestamp", "desc").get();
  // transform infomation
  const docs = posts.docs.map((post) => ({
    id: post.id,
    ...post.data(),
    timestamp: null,
  }));
  return {
    props: {
      session,
      posts: docs,
    },
  };
}
